# Generated by Django 5.2.14 on 2026-05-30 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('suspects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('entity', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='stations.policestation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('crime_category', models.CharField(choices=[('theft', 'Theft'), ('assault', 'Assault'), ('robbery', 'Robbery'), ('fraud', 'Fraud'), ('cyber', 'Cybercrime'), ('other', 'Other')], max_length=32)),
                ('location', models.CharField(max_length=256)),
                ('narrative', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('closed', 'Closed')], default='open', max_length=20)),
                ('modus_operandi', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='stations.policestation')),
            ],
            options={
                'ordering': ['-opened_at'],
                'unique_together': {('station', 'case_number')},
            },
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('storage_path', models.CharField(blank=True, max_length=512)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='MOTagOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('target', 'Target Type'), ('entry', 'Entry Method'), ('weapon', 'Weapon Class'), ('timeframe', 'Timeframe'), ('escape', 'Escape Method')], max_length=32)),
                ('value', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'label'],
                'unique_together': {('category', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('contact', models.CharField(blank=True, max_length=128)),
                ('statement', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseSuspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='suspect', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_suspects', to='cases.case')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_links', to='suspects.suspect')),
            ],
            options={
                'unique_together': {('case', 'suspect')},
            },
        ),
    ]
