# Generated by Codex on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidenceitem",
            name="file_size",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
