"""Executive Excel report generation for regional command."""

from io import BytesIO
import os

from django.conf import settings
from django.utils import timezone
from openpyxl import Workbook
from openpyxl.drawing.image import Image as XLImage
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from apps.analytics.pattern_matcher import precinct_performance, subcounty_hotspots
from apps.cases.models import Case


def build_precinct_workbook() -> bytes:
    wb = Workbook()

    # --- Style Definitions ---
    font_title = Font(name="Calibri", size=15, bold=True, color="1E3A8A")
    font_meta = Font(name="Calibri", size=9, italic=True, color="64748B")
    font_header = Font(name="Calibri", size=11, bold=True, color="FFFFFF")

    fill_header = PatternFill(start_color="1E3A8A", end_color="1E3A8A", fill_type="solid")
    fill_zebra = PatternFill(start_color="F8FAFC", end_color="F8FAFC", fill_type="solid")
    fill_white = PatternFill(start_color="FFFFFF", end_color="FFFFFF", fill_type="solid")

    # Status Fills & Fonts
    fill_open = PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid")
    font_open = Font(name="Calibri", size=10, bold=True, color="92400E")

    fill_investigating = PatternFill(start_color="DBEAFE", end_color="DBEAFE", fill_type="solid")
    font_investigating = Font(name="Calibri", size=10, bold=True, color="1E40AF")

    fill_closed = PatternFill(start_color="D1FAE5", end_color="D1FAE5", fill_type="solid")
    font_closed = Font(name="Calibri", size=10, bold=True, color="065F46")

    thin_border_side = Side(border_style="thin", color="CBD5E1")
    border_data = Border(left=thin_border_side, right=thin_border_side, top=thin_border_side, bottom=thin_border_side)
    border_header = Border(left=thin_border_side, right=thin_border_side, top=thin_border_side, bottom=Side(border_style="medium", color="0F172A"))

    align_center = Alignment(horizontal="center", vertical="center")
    align_left = Alignment(horizontal="left", vertical="center")
    align_right = Alignment(horizontal="right", vertical="center")

    gen_time_str = timezone.localtime(timezone.now()).strftime("%Y-%m-%d %H:%M:%S")

    # Helper for adding title banner
    def add_title_banner(ws, title_text, start_row=1):
        ws.views.sheetView[0].showGridLines = True
        ws.cell(row=start_row, column=1, value=title_text).font = font_title
        meta_str = f"Generated by LexGuard Command Platform on {gen_time_str} | Classification: CONFIDENTIAL / OFFICIAL POLICE USE ONLY"
        ws.cell(row=start_row + 1, column=1, value=meta_str).font = font_meta

    # =========================================================================
    # SHEET 1: Regional Cases (Detailed Registry)
    # =========================================================================
    ws_cases = wb.active
    ws_cases.title = "Regional Cases"
    add_title_banner(ws_cases, "COAST REGION POLICE COMMAND — REGIONAL CASE REGISTRY", start_row=1)

    headers_cases = [
        "Case Number",
        "Station Code",
        "Station Name",
        "County",
        "Crime Category",
        "Case Title",
        "Incident Location",
        "Status",
        "Opened At",
        "Closed At",
    ]

    header_row_cases = 4
    ws_cases.row_dimensions[header_row_cases].height = 26
    for col_idx, h in enumerate(headers_cases, 1):
        cell = ws_cases.cell(row=header_row_cases, column=col_idx, value=h)
        cell.font = font_header
        cell.fill = fill_header
        cell.alignment = align_center
        cell.border = border_header

    cases_qs = Case.objects.select_related("station").order_by("-opened_at")
    for idx, case in enumerate(cases_qs):
        row_idx = header_row_cases + 1 + idx
        ws_cases.row_dimensions[row_idx].height = 20
        fill_row = fill_zebra if idx % 2 == 1 else fill_white

        opened_str = timezone.localtime(case.opened_at).strftime("%Y-%m-%d %H:%M") if case.opened_at else ""
        closed_str = timezone.localtime(case.closed_at).strftime("%Y-%m-%d %H:%M") if case.closed_at else ""
        status_disp = case.get_status_display() if hasattr(case, "get_status_display") else case.status

        c1 = ws_cases.cell(row=row_idx, column=1, value=case.case_number)
        c2 = ws_cases.cell(row=row_idx, column=2, value=case.station.code)
        c3 = ws_cases.cell(row=row_idx, column=3, value=case.station.name)
        c4 = ws_cases.cell(row=row_idx, column=4, value=case.station.county)
        c5 = ws_cases.cell(row=row_idx, column=5, value=case.get_crime_category_display() if hasattr(case, "get_crime_category_display") else case.crime_category)
        c6 = ws_cases.cell(row=row_idx, column=6, value=case.title)
        c7 = ws_cases.cell(row=row_idx, column=7, value=case.location)
        c8 = ws_cases.cell(row=row_idx, column=8, value=status_disp)
        c9 = ws_cases.cell(row=row_idx, column=9, value=opened_str)
        c10 = ws_cases.cell(row=row_idx, column=10, value=closed_str)

        c1.alignment = align_center
        c2.alignment = align_center
        c3.alignment = align_left
        c4.alignment = align_left
        c5.alignment = align_left
        c6.alignment = align_left
        c7.alignment = align_left
        c8.alignment = align_center
        c9.alignment = align_center
        c10.alignment = align_center

        for cell in [c1, c2, c3, c4, c5, c6, c7, c8, c9, c10]:
            cell.fill = fill_row
            cell.border = border_data

        # Custom status pill styling
        if case.status == "open":
            c8.fill = fill_open
            c8.font = font_open
        elif case.status == "investigating":
            c8.fill = fill_investigating
            c8.font = font_investigating
        elif case.status == "closed":
            c8.fill = fill_closed
            c8.font = font_closed

    # =========================================================================
    # SHEET 2: Precinct Performance
    # =========================================================================
    ws_perf = wb.create_sheet("Precinct Performance")

    logo_path = os.path.join(settings.BASE_DIR, "static", "images", "Logo.jpg")
    start_row = 1
    if os.path.exists(logo_path):
        try:
            img = XLImage(logo_path)
            img.width = 160
            img.height = 55
            ws_perf.add_image(img, "A1")
            start_row = 5
        except Exception:
            start_row = 1

    add_title_banner(ws_perf, "COAST REGION POLICE COMMAND — PRECINCT PERFORMANCE MATRIX", start_row=start_row)

    headers_perf = ["Station Code", "Station Name", "County", "Open Cases", "Closed Cases", "Closure Rate", "Avg Resolution Days"]
    header_row_perf = start_row + 3
    ws_perf.row_dimensions[header_row_perf].height = 26
    for col_idx, h in enumerate(headers_perf, 1):
        cell = ws_perf.cell(row=header_row_perf, column=col_idx, value=h)
        cell.font = font_header
        cell.fill = fill_header
        cell.alignment = align_center
        cell.border = border_header

    perf_data = precinct_performance()
    for idx, row in enumerate(perf_data):
        row_idx = header_row_perf + 1 + idx
        ws_perf.row_dimensions[row_idx].height = 20
        fill_row = fill_zebra if idx % 2 == 1 else fill_white

        c1 = ws_perf.cell(row=row_idx, column=1, value=row["station"].code)
        c2 = ws_perf.cell(row=row_idx, column=2, value=row["station"].name)
        c3 = ws_perf.cell(row=row_idx, column=3, value=row["station"].county)
        c4 = ws_perf.cell(row=row_idx, column=4, value=row["open"])
        c5 = ws_perf.cell(row=row_idx, column=5, value=row["closed"])
        c6 = ws_perf.cell(row=row_idx, column=6, value=row["closure_rate"] / 100.0)
        c7 = ws_perf.cell(row=row_idx, column=7, value=row["avg_resolution_days"] or 0)

        c1.alignment = align_center
        c2.alignment = align_left
        c3.alignment = align_left
        c4.alignment = align_right
        c5.alignment = align_right
        c6.alignment = align_right
        c7.alignment = align_right

        c6.number_format = "0.0%"
        c7.number_format = '0.0 "days"'

        for cell in [c1, c2, c3, c4, c5, c6, c7]:
            cell.fill = fill_row
            cell.border = border_data

    # =========================================================================
    # SHEET 3: Sub-County Hotspots
    # =========================================================================
    ws_hotspots = wb.create_sheet("Sub-County Hotspots")
    add_title_banner(ws_hotspots, "COAST REGION POLICE COMMAND — SUB-COUNTY CRIME HOTSPOTS", start_row=1)

    headers_hotspots = ["Sub-County Jurisdiction", "County", "Crime Category", "Total Case Count"]
    header_row_hotspots = 4
    ws_hotspots.row_dimensions[header_row_hotspots].height = 26
    for col_idx, h in enumerate(headers_hotspots, 1):
        cell = ws_hotspots.cell(row=header_row_hotspots, column=col_idx, value=h)
        cell.font = font_header
        cell.fill = fill_header
        cell.alignment = align_center
        cell.border = border_header

    hotspots_data = subcounty_hotspots()[:50]
    for idx, row in enumerate(hotspots_data):
        row_idx = header_row_hotspots + 1 + idx
        ws_hotspots.row_dimensions[row_idx].height = 20
        fill_row = fill_zebra if idx % 2 == 1 else fill_white

        c1 = ws_hotspots.cell(row=row_idx, column=1, value=row["station__sub_county"] or "Unspecified")
        c2 = ws_hotspots.cell(row=row_idx, column=2, value=row["station__county"])
        c3 = ws_hotspots.cell(row=row_idx, column=3, value=row["crime_category"].capitalize())
        c4 = ws_hotspots.cell(row=row_idx, column=4, value=row["count"])

        c1.alignment = align_left
        c2.alignment = align_left
        c3.alignment = align_left
        c4.alignment = align_right

        for cell in [c1, c2, c3, c4]:
            cell.fill = fill_row
            cell.border = border_data

    # =========================================================================
    # Auto-adjust column widths for all sheets
    # =========================================================================
    for ws in [ws_cases, ws_perf, ws_hotspots]:
        for col in ws.columns:
            max_len = 0
            col_letter = get_column_letter(col[0].column)
            for cell in col:
                val_str = str(cell.value or "")
                # Ignore long title row strings when computing width
                if cell.row < 4:
                    continue
                if len(val_str) > max_len:
                    max_len = len(val_str)
            ws.column_dimensions[col_letter].width = max(max_len + 4, 14)

    buffer = BytesIO()
    wb.save(buffer)
    return buffer.getvalue()
