# Generated by Django 5.2.14 on 2026-07-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='suspects/photos/'),
        ),
    ]
